require "./kafkaesque/object_pool"
require "./kafkaesque/protocol/types"
require "./kafkaesque/protocol/request"
require "./kafkaesque/protocol/response"
require "./kafkaesque/protocol/metadata"
require "./kafkaesque/protocol/sasl"
require "./kafkaesque/protocol/produce_fetch"
require "./kafkaesque/protocol/compression"
require "./kafkaesque/protocol/group_coordinator"
require "./kafkaesque/protocol/init_producer_id"
require "./kafkaesque/protocol/api_versions"
require "./kafkaesque/protocol/share_groups"
require "./kafkaesque/protocol/telemetry"
require "./kafkaesque/protocol/transactions"
require "./kafkaesque/protocol/scram"
require "./kafkaesque/backoff"
require "./kafkaesque/partitioner"
require "./kafkaesque/connection"
require "./kafkaesque/client"
require "./kafkaesque/topic_partition"
require "./kafkaesque/consumer"
require "./kafkaesque/producer"
require "./kafkaesque/metrics_server"
require "./kafkaesque/tracing"
require "./kafkaesque/config_loader"

require "log"
require "http/client"
require "uri"

module Kafkaesque
  VERSION = "2.3.1"
  Log     = ::Log.for("kafkaesque")
end
